services:
  oracle-apex:
    image: gvenzl/oracle-xe:21-full
    container_name: oracle_bus
    restart: always
    ports:
      - "1521:1521"  # Puerto DB para Spring
      - "8181:8080"  # Puerto Web para APEX
    environment:
      - ORACLE_PASSWORD=root_pass_123
      - APP_USER=bus_user
      - APP_USER_PASSWORD=bus_pass_123
    volumes:
      - oracle_data:/opt/oracle/oradata

  backend:
    build: .
    container_name: spring_backend
    ports:
      - "8080:8080"
    depends_on:
      - oracle-apex
    environment:
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@oracle-apex:1521/XE
      - SPRING_DATASOURCE_USERNAME=system
      - SPRING_DATASOURCE_PASSWORD=root_pass_123
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=oracle.jdbc.OracleDriver

volumes:
  oracle_data: