spring.application.name=BackendTFG
frontendWeb=rutaAWeb
frontendMovil=rutaAMovil
rutaAGPS=rutaAGPS
rutaABaseDeDatos=rutaBD
ors.api.key=eyJvcmciOiI1YjNjZTM1OTc4NTExMTAwMDFjZjYyNDgiLCJpZCI6ImU5YmY5ZGU0OWMyOTRiOGE4NDY1OGQxZDI0NDY3YzVjIiwiaCI6Im11cm11cjY0In0=
ors.api.url=https://api.openrouteservice.org/v2
server.port=8080

 #Esto por si arranco desde java y no desde docker
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/FREEPDB1
spring.datasource.username=MARCHENA_BUS
spring.datasource.password=Marchena_2026!
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

