-- 1. Tabla CIUDAD
CREATE TABLE ciudad (
                        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        nombre VARCHAR2(150) NOT NULL,
                        provincia VARCHAR2(150),
                        pais VARCHAR2(150) DEFAULT 'España'
);

-- 2. Tabla LINEA_BUS
CREATE TABLE linea_bus (
                           id NUMBER PRIMARY KEY,
                           nombre_linea VARCHAR2(200),
                           ciudad_origen NUMBER,
                           ciudad_destino NUMBER,
                           CONSTRAINT fk_ciudad_origen FOREIGN KEY (ciudad_origen) REFERENCES ciudad(id),
                           CONSTRAINT fk_ciudad_destino FOREIGN KEY (ciudad_destino) REFERENCES ciudad(id)
);

-- 3. Tabla PARADA (Incluyendo soporte Spatial)
CREATE TABLE parada (
                        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        nombre VARCHAR2(255) NOT NULL,
                        latitud NUMBER,
                        longitud NUMBER,
                        id_ciudad NUMBER NOT NULL,
    -- Columna para cálculos espaciales (Rutas, cercanía)
                        geom SDO_GEOMETRY,
                        CONSTRAINT fk_id_ciudad FOREIGN KEY (id_ciudad) REFERENCES ciudad(id)
);

-- 4. Tabla LINEA_PARADA
CREATE TABLE linea_parada (
                              id_linea NUMBER,
                              id_parada NUMBER,
                              orden NUMBER,
                              tiempo_siguiente_min NUMBER,
                              distancia_siguiente_km NUMBER,
                              PRIMARY KEY (id_linea, id_parada),
                              CONSTRAINT fk_linea FOREIGN KEY (id_linea) REFERENCES linea_bus(id),
                              CONSTRAINT fk_parada FOREIGN KEY (id_parada) REFERENCES parada(id)
);

-- 5. Tabla ROUTE
CREATE TABLE route (
                       id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       nombre VARCHAR2(200) NOT NULL,
                       linea_bus_id NUMBER NOT NULL,
                       CONSTRAINT fk_linea_bus_route FOREIGN KEY (linea_bus_id) REFERENCES linea_bus(id)
);

-- 6. Tabla AI_CHAT_LOG
CREATE TABLE ai_chat_log (
                             id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             pregunta CLOB NOT NULL, -- Usamos CLOB para textos largos
                             respuesta CLOB NOT NULL,
                             fecha_registro TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 7. Tabla CONDUCTOR_AUTH
CREATE TABLE conductor_auth (
                                id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                bus_id VARCHAR2(50) NOT NULL UNIQUE,
                                password VARCHAR2(255) NOT NULL,
                                nombre_conductor VARCHAR2(150),
                                id_linea_asignada NUMBER,
                                CONSTRAINT fk_linea_asignada FOREIGN KEY (id_linea_asignada) REFERENCES linea_bus(id)
);

-- ==========================================
-- INSERCIÓN DE DATOS ADAPTADOS
-- ==========================================

-- CIUDADES
INSERT INTO ciudad (nombre, provincia) VALUES ('Marchena', 'Sevilla');
INSERT INTO ciudad (nombre, provincia) VALUES ('La Puebla de Cazalla', 'Sevilla');
INSERT INTO ciudad (nombre, provincia) VALUES ('Arahal', 'Sevilla');
INSERT INTO ciudad (nombre, provincia) VALUES ('Osuna', 'Sevilla');

-- LINEAS DE BUS
INSERT INTO linea_bus (id, nombre_linea, ciudad_origen, ciudad_destino) VALUES (140, 'M-140', 1, 2);
INSERT INTO linea_bus (id, nombre_linea, ciudad_origen, ciudad_destino) VALUES (141, 'M-141', 1, 3);
INSERT INTO linea_bus (id, nombre_linea, ciudad_origen, ciudad_destino) VALUES (142, 'M-142', 1, 4);

-- PARADAS (Insertamos coordenadas y creamos el objeto Geometry)
-- Nota: En Oracle Spatial es (Longitud, Latitud) -> (X, Y)
INSERT INTO parada (nombre, latitud, longitud, id_ciudad, geom)
VALUES ('Estación de Autobuses de Marchena', 37.3309, -5.4172, 1,
        SDO_GEOMETRY(2001, 8307, SDO_POINT_TYPE(-5.4172, 37.3309, NULL), NULL, NULL));

INSERT INTO parada (nombre, latitud, longitud, id_ciudad, geom)
VALUES ('Avenida Maestro Santos Ruano', 37.3275, -5.4150, 1,
        SDO_GEOMETRY(2001, 8307, SDO_POINT_TYPE(-5.4150, 37.3275, NULL), NULL, NULL));

-- (Repetir el patrón para el resto de paradas...)

-- CONDUCTORES
INSERT INTO conductor_auth (bus_id, password, nombre_conductor, id_linea_asignada)
VALUES ('bus-101', 'tfg2024', 'Juan Pérez', 140);

COMMIT;